= aerospace-list-apps(1)
include::util/man-attributes.adoc[]
:manname: aerospace-list-apps
// tag::purpose[]
:manpurpose: Print applications owning windows managed by AeroSpace
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospace list-apps [-h|--help] [--format <output-format>] [--count] [--json]

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

The command is useful to inspect list of applications to compose filter for xref:guide.adoc#on-window-detected-callback[on-window-detected callback]

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help


--format <output-format>:: Specify output format. See "Output Format" section for more details.
Incompatible with `--count`

--count:: Output only the number of apps.
Incompatible with: `--format`, `--json`

--json:: Output in JSON format.
Can be used in combination with `--format` to specify which data to include into the json.
Incompatible with `--count`

// =========================================================== Output Format
include::util/conditional-output-format-header.adoc[]

Output format can be configured with optional `[--format <output-format>]` option.
`<output-format>` supports https://en.wikipedia.org/wiki/String_interpolation[string interpolation].

If not specified, the default `<output-format>` is: +
`%{app-pid}%{right-padding} | %{app-id}%{right-padding} | %{app-name}`

The following variables can be used inside `<output-format>`:

%{app-id}:: String. Application executable filename in lowercase, such as `notepad.exe`
%{app-name}:: String. Application name
%{app-pid}:: Number. Windows process identifier
%{app-exec-path}:: String. Application executable path
%{app-executable-directory}:: String. Directory containing the application executable

%{right-padding}:: A special variable which expands with a minimum number of spaces required to form a right padding in the appropriate column
%{newline}:: Unicode U+000A newline symbol `\n`
%{tab}:: Unicode U+0009 tab symbol `\t`

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
